#!/usr/bin/env python3
"""Calculate a BOM total from a generated Digi-Key price CSV."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import digikey_bom_common as bom_common


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "price_csv",
        nargs="?",
        default="bom/nixie_clock_digikey_price_list.csv",
        help="CSV generated by tools/digikey_bom_price.py.",
    )
    parser.add_argument("--pretty", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    with Path(args.price_csv).open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    total = bom_common.total_from_price_rows(rows)
    output = {
        "ok": True,
        "price_csv": args.price_csv,
        "rows": len(rows),
        "total_jpy": str(total),
    }
    print(json.dumps(output, ensure_ascii=False, indent=2 if args.pretty else None))
    return 0


if __name__ == "__main__":
    sys.exit(main())
